import groovy.sql.Sql

def sql = Sql.newInstance("jdbc:mysql://localhost:3306/mydb",
        "user", "pswd", "com.mysql.jdbc.Driver")

sql.execute '''
  CREATE TABLE Data (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    first_name   VARCHAR(64),
    last_name    VARCHAR(64),
    birth_date  VARCHAR(64)
'''

def firstName
def lastName
def birthDate
int lineCounter = 0

new File("data.csv")?.splitEachLine(",") { fields ->

    firstName = fields[0].getClass() == "String" ? fields[0] : "First name not available"
    lastName = fields[1].getClass() == "String" ? fields[1] : "Last name not available"
    birthDate = fields[2] != null && fields[2] != "" ? Date.parseToStringDate(fields[2]).format("yyyy-MM-dd") : "Birth date not available"

    lineCounter += 1

    sql.execute "INSERT INTO Data (first_name, last_name, birth_date) VALUES (firstName, lastName, birthDate)"

    println("Adding line #${lineCounter} with values:" +
            "First name: ${firstName}" +
            "Last name: ${lastName}" +
            "Birth date: ${birthDate}")
}
